name: MPAreaSpawner
version: ${project.version}
main: com.popupmc.areaspawner.AreaSpawner
api-version: 1.15
authors: [lelesape]
description: ${project.description}
website: http://bit.ly/2mwvHWN
softdepend: [Essentials, MultiverseCore, Vault]

commands:
  areaSpawner:
    description: Admin command for AreaSpawner
    aliases: [as]
    usage: Command was not registered properly
  randomSpawn:
    description: User command for AreaSpawner
    aliases: [rs, rspawn]
    usage: Command was not registered properly

permissions:
  areaSpawner.version:
    description: Allows you to check the plugins version
    default: op
  areaSpawner.reload:
    description: Allows you to reload the plugin
    default: op
  areaSpawner.locations:
    description: Allows you to see how many safe to spawn locations are currently stored in cache.
    default: op
  areaSpawner.regenerate:
    description: Allows you to regenerate safe spawn locations
    default: op
  areaSpawner.automatic:
    description: Allows you to be automatically teleported.
    default: op
  areaSpawner.travel:
    description: Allows you to teleport manually using the travel command.
    default: op
  areaSpawner.forceTravel:
    description: Allows you to force a player to teleport to a new random location.
    default: op
  areaSpawner.cooldown.bypass:
    description: Allows a player to bypass travel command cooldowns when these are enabled.
    default: op
  areaSpawner.*:
    description: Gives access to every permission available
    default: op
    children:
      areaSpawner.version: true
      areaSpawner.reload: true
      areaSpawner.locations: true
      areaSpawner.regenerate: true
      areaSpawner.automatic: true
      areaSpawner.forceTravel: true
      areaSpawner.travel: true
      areaSpawner.cooldown.bypass: true